### ISSUE TITLE
Connection aborted issue

### ISSUE THREAD

**Issue by muhammedfurkan** [lestex/udemydl#1]
I am getting this error:
`requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

**Comment by lestex** [comment]
Just checked with this configuration, it works:
```python -V
Python 3.7.6

pip install udemydl

udemydl course_url
Username / Email : udemy_login
Password: **
INFO     Trying to log in ...
INFO     Login success.
INFO     Analyzing the course ...
INFO     Downloading files ...
INFO     Downloading lecture: 02 - course video.mp4
###############################################################################56.9%^C
INFO     Logged Out!
ERROR    User interrupted the process, exiting...
```
The OS I'm using is Macos

**Comment by lestex** [comment]
You have to be enrolled in the course you want to download.

**Comment by muhammedfurkan** [comment]
> Just checked with this configuration, it works:
> 
> ```python
> Python 3.7.6
> 
> pip install udemydl
> 
> udemydl course_url
> Username / Email : udemy_login
> Password: **
> INFO     Trying to log in ...
> INFO     Login success.
> INFO     Analyzing the course ...
> INFO     Downloading files ...
> INFO     Downloading lecture: 02 - course video.mp4
> ###############################################################################56.9%^C
> INFO     Logged Out!
> ERROR    User interrupted the process, exiting...
> ```
> 
> The OS I'm using is Macos

I am using from Google Colab

**Comment by lestex** [comment]
I'm not sure I can help you with that
